name: cleanup
run-name: ${{ inputs.aws_bucket_instance_name }}

on:  {push}
jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout root repo
        uses: actions/checkout@v4
        
      # - name: Get env files
      #   run: npx --yes dotenv-vault pull --dotenvMe  ci .env.ci
    
      # - name: Load .env file
      #   run: grep -o '^[^#]*' .env.ci >> "$GITHUB_ENV"
        
      
      # - name: Delete bucket
      #   run: aws s3api delete-bucket --bucket ${{ inputs.aws_bucket_instance_name }} --region eu-west-3
